# A self-singed temporary certificate is used in this sample, so that the sample can be run without any dependencies,
# and the certificate can be validated. In production environment, a valid certificate should be used.
- name: create temporary directory for certificates
  tempfile:
    state: directory
    suffix: cert
  register: result

- set_fact:
    cert_path: "{{ result.path }}"

- name: Generate CA Cert Key
  openssl_privatekey:
    path: "{{cert_path}}/ca_key.pem"
    type: RSA
    size: 2048

- name: Generate CA cert
  command: openssl req \
        -x509 -new -days 365 \
        -subj '/C=IN/ST=KA/L=mylocation/O=Ansible/CN=www.ansible.oracle.com'
        -key "{{cert_path}}/ca_key.pem" \
        -out "{{cert_path}}/ca_cert.pem"
  args:
      creates: "{{cert_path}}/ca_cert.pem"

- name: Generate Server Private Key Without Passphrase
  openssl_privatekey:
      path: "{{cert_path}}/private_key.pem"
      type: RSA
      size: 2048

- name: Generate Certificate Signing Request With Normal Private Key
  openssl_csr:
    path: "{{cert_path}}/csr.pem"
    privatekey_path: "{{cert_path}}/private_key.pem"
    country_name: IN
    organization_name: Ansible
    state_or_province_name: KA
    locality_name: Bangalore
    common_name: www.ansible.oracle.com

- name: Generate CA signed Certificate Without Passphrase
  command: openssl x509 -req \
        -days 1825 -CA "{{cert_path}}/ca_cert.pem" -CAkey "{{cert_path}}/ca_key.pem" -CAcreateserial \
        -in "{{cert_path}}/csr.pem" \
        -out "{{cert_path}}/cert.pem"
  args:
    creates: "{{cert_path}}/cert.pem"
