---

- name: Create a bastion subnet
  oci_subnet:
    availability_domain: "{{ bastion_availability_domain }}"
    cidr_block: "{{ bastion_subnet_cidr_block }}"
    compartment_id: "{{ demo_compartment_ocid }}"
    display_name: "{{ demo_bastion_subnet_name }}"
    prohibit_public_ip_on_vnic: false
    security_list_ids: [ "{{ bastion_security_list_ocid }}" ]
    vcn_id: '{{ demo_vcn_ocid }}'
    dns_label: "{{ demo_bastion_subnet_dns_label }}"
    route_table_id: "{{ demo_core_rt_ig_ocid }}"
  register: result

- set_fact:
    bastion_subnet_ocid: "{{ result.subnet.id }}"
