---

- name: get bastion ID
  oci_instance_facts:
    availability_domain: "{{ bastion_availability_domain }}"
    compartment_id: "{{ demo_compartment_ocid }}"
    display_name: "{{ demo_bastion_instance_name }}"
    lifecycle_state: 'RUNNING'
  register: bastion

- name: Include task list to create bastion server
  include_tasks: "create_server.yaml"
  when: bastion.instances|length==0

- set_fact:
    ssh_extra_args: "-o StrictHostKeyChecking=no -i {{ demo_ssh_private_key }} -o ProxyCommand='ssh -o StrictHostKeyChecking=no -i {{ demo_ssh_private_key }} -W %h:%p -q opc@{{ bastion.instances[0].primary_public_ip }}'"
    when: bastion.instance|length==1
