title: "Deploy a fully managed APEX instance"
description: "Deploy the APEX low-code application development platform as a standalone OCI managed service"
schemaVersion: 1.1.0
version: "20190304"
locale: "en"

variableGroups:
- title: General Configuration
  visible: false
  variables:
  - tenancy_ocid
  - region
  - compartment_ocid

- title: Apex Configuration
  visible: true  
  variables:
    - autonomous_database_admin_password
outputs:
  apex_url:
    type: link
    title: Apex Login
    description: Open Apex
primaryOutputButton: apex_url

variables:
  autonomous_database_admin_password:
    type: password
    required: true
    title: "Apex password"
    description: "Password must at least 12 characters long and include at least one uppercase letter, one lowercase letter, and one numeric character"
    pattern: "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?]).{8,32}$"
    visible: true
  compartment_ocid:
    type: oci:identity:compartment:id
    title: "Compartment"
    description: "The compartment in which to create Apex instance"
    required: true
      

