- name: Create a temporary directory to house a temporary SSH keypair to connect to bastion instance
  tempfile:
    state: directory
    suffix: cert
  register: result
  
- set_fact:
    temp_certificates_path: "{{ result.path }}"
    
- name: Generate a Private Key
  openssl_privatekey:
    path: "{{ temp_certificates_path }}/private_key.pem"
    type: RSA
    size: 2048
    
- set_fact:
    demo_ssh_public_key: "{{ temp_certificates_path }}/public_key.pem"
    
- name: Generate a Public Key
  openssl_publickey:
    path: "{{ demo_ssh_public_key }}"
    privatekey_path: "{{ temp_certificates_path }}/private_key.pem"
    format: OpenSSH

- debug:
    msg: "Using generated keys at {{ temp_certificates_path }} to launch instances."

- set_fact:
    demo_ssh_private_key: "{{ temp_certificates_path }}/private_key.pem"
